# Generated by Django 6.1.1 on 2026-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mechshop_DB',
            fields=[
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('vehicle_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('bike_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
            ],
        ),
    ]
